# Generated by Django 2.0 on 2018-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidataId', models.CharField(max_length=255, verbose_name='Wikidata ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
    ]
